import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  return [
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/',
      lastModified,
      changeFrequency: 'monthly',
      priority: 1,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/aspagh',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_rakhis',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_shatir',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/muealim_sabagh',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/aisbgh_alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_shatir_bi_alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/muealim_sabaagh_bi_alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/faniy_sabagh',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_mumtaz_bi_alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/dikurat_sabagh_lilkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/manazil_sabaagh_bi_alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/shaqaq_sabaagh_bi_alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_buyut_aitfal',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_rusumat_aitfal',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_rakhisat_bi_alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/dihanat_alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/tarkib_waraq_judran',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/asbagh_abwab_khashabia',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/muealim_jabs_burd',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alsaalimia',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_sabah_alsaalim',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_hawalli',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_jaber_alahmad',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_khaitan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alfarwaniyah',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_aljabriya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alshaab',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_bayan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_janoub_alsura',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_mubarak',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_mishref',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alzahraa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alsiddiq',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_hateen',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_salwa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alshuhadaa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_al_salam',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_al_masila',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_almasayel',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_abu_alhasania',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_subhan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_abu_ftaira',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_al_fintas',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_mubarak_al_kabeer',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alaqeela',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alfntas',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alraqa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_abu_halifa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alsabahiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_almanqaf',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_almahboula',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_al_ahmadi',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_al_khiran',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alfhahil',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alwafra',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_jaber_alali',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_fahad_alahmad',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_aldaiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_aldasma',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_aldohah',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alkhaldiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alrawdah',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alrai',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alshuwaykh',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_asharq',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alshamiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alsurra',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alqadesiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alqurawan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alfaihaa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_aladiliya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alsulaybikhat',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_kaifan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_qurtoba',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_ghranata',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_abdullah_al_salim',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_dasman',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_bneid_alqar',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alnahda',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alnuzha',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_almansouriya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_mantiqa_al_ashira',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alandalus',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alqrean',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_alkswor',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh_aladaan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
  ];
}
