import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  return [
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/',
      lastModified,
      changeFrequency: 'monthly',
      priority: 1,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/aspagh',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-rakhis',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-shatir',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/muealim-sabagh',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/aisbgh-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-shatir-bi-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/muealim-sabaagh-bi-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/faniy-sabagh',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-mumtaz-bi-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/dikurat-sabagh-lilkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/manazil-sabaagh-bi-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/shaqaq-sabaagh-bi-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-buyut-aitfal',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-rusumat-aitfal',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-rakhisat-bi-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/dihanat-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/tarkib-waraq-judran',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/asbagh-abwab-khashabia',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/muealim-jabs-burd',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alsaalimia',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-sabah-alsaalim',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-hawalli',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-jaber-alahmad',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-khaitan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alfarwaniyah',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-aljabriya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alshaab',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-bayan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-janoub-alsura',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-mubarak',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-mishref',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alzahraa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alsiddiq',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-hateen',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-salwa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alshuhadaa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-al-salam',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-al-masila',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-almasayel',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-abu-alhasania',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-subhan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-abu-ftaira',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-al-fintas',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-mubarak-al-kabeer',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alaqeela',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alfntas',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alraqa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-abu-halifa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alsabahiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-almanqaf',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-almahboula',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-al-ahmadi',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-al-khiran',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alfhahil',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alwafra',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-jaber-alali',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-fahad-alahmad',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-aldaiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-aldasma',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-aldohah',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alkhaldiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alrawdah',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alrai',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alshuwaykh',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-asharq',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alshamiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alsurra',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alqadesiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alqurawan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alfaihaa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-aladiliya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alsulaybikhat',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-kaifan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-qurtoba',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-ghranata',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-abdullah-al-salim',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-dasman',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-bneid-alqar',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alnahda',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alnuzha',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-almansouriya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-mantiqa-al-ashira',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alandalus',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alqrean',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-alkswor',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://apartment-paint-kuwait.mountain-egy.site/sabaagh-aladaan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
  ];
}
